DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS tests_result;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS materials;
DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;